### ISSUE TITLE
Send PR to PostCSS docs/plugins.md

### ISSUE THREAD

**Issue by ai** [rtsao/postcss-rtlcss-combined#1]
Also maybe you should send link to RTLCSS author

**Comment by MohammadYounes** [comment]
Nice work! I adore the re-usability you have made :+1: 

Unfortunately, this method is error-prone, as it messes with rules specificity  :disappointed:. 

Example CSS:

``` CSS
body h1 {
  border-style:dashed dotted solid double;
  border-color:red green blue black;
  border-width: 1px 2px 3px 4px;
}
div h1 {
  border-color:green;
}
```

The combined version:

``` CSS
body h1 {
  border-style: dashed dotted solid double;
  border-color: red green blue black;
  border-width: 1px 2px 3px 4px
}
div h1{
  border-color: green
}

html[dir="rtl"] body h1 {
  border-style: dashed double solid dotted;
  border-color: red black blue green;
  border-width: 1px 4px 3px 2px
}
```

In the LTR version `div h1` has higher specificity, but in the RTL version, the specificity of `html[dir="rtl"] body h1` will be higher ([JSFiddle](http://jsfiddle.net/v57tubw3/)).

---

##### What about moving all the directional declarations into a separate rule ?

The same problem still exists!, let's make a slight change in the example CSS:

``` CSS
body h1 {
    border-style: dashed dotted solid double;
    border-color: red green blue black;
    border-width: 1px 2px 3px 4px
}
body h1:not(:last-child) {
    border-color: green
}
```

Then combine it with separate rules:

``` CSS
body h1:not(:last-child) {
    border-color: green
}
html[dir="ltr"] body h1 {
    border-style: dashed dotted solid double;
    border-color: red green blue black;
    border-width: 1px 2px 3px 4px
}
html[dir="rtl"] body h1 {
    border-style: dashed double solid dotted;
    border-color: red black blue green;
    border-width: 1px 4px 3px 2px
}
```

In the original CSS `body h1:not(:last-child)` has higher specificity and should render the **h1** with **green** border, But in the combined version,  the specificity of  `html[dir="ltr"] body h1` will be higher. ([JSFiddle](http://jsfiddle.net/t60xkfgk/)).

I walked down this road before and I thought you should know the cons of using this approach.

Thanks!

**Comment by rtsao** [comment]
@MohammadYounes Thanks for pointing that out!

It seems then that prepending every common/overridable rule with `html[dir]` should solve the specificity issues you described. For example:

Original

``` css
body h1:not(:last-child) {
    border-color: green
}
body h1 {
    border-style: dashed dotted solid double;
    border-color: red green blue black;
    border-width: 1px 2px 3px 4px
}
```

Combined

``` css
html[dir] body h1:not(:last-child) {
    border-color: green
}
html[dir="ltr"] body h1 {
    border-style: dashed dotted solid double;
    border-color: red green blue black;
    border-width: 1px 2px 3px 4px
}
html[dir="rtl"] body h1 {
    border-style: dashed double solid dotted;
    border-color: red black blue green;
    border-width: 1px 4px 3px 2px
}
```

([JSFiddle](http://jsfiddle.net/t60xkfgk/1/))
