### ISSUE TITLE
Type error when input CSS has no directional properties

### ISSUE THREAD

**Issue by MohammadYounes** [rtsao/postcss-rtlcss-combined#3]
The following input:

``` css
div {
    display: block;   
}
```

Produces:  **[TypeError: Cannot read property 'div' of undefined]**
