### ISSUE TITLE
Remove empty rules

### ISSUE THREAD

**Issue by MohammadYounes** [rtsao/postcss-rtlcss-combined#4]
The following input:

``` css
div {
    display: block; 
    float: left;
}
```

Produces:

``` css
div {
    display: block;
    float: left
}
html[dir="ltr"] div {}
html[dir="rtl"] div {
    float: right
}
```
