### ISSUE TITLE
Prefix all selectors

### ISSUE THREAD

**Issue by MohammadYounes** [rtsao/postcss-rtlcss-combined#5]
The following input:

``` css
.a , .b {
    text-align: right;
}
```

Produces:

``` CSS
.a , .b {
    text-align: right
}
html[dir="ltr"] .a , .b {}
html[dir="rtl"] .a , .b {
    text-align: left
}
```

Note that `.b` is not prefixed.
