### ISSUE TITLE
Duplicate selector is lost

### ISSUE THREAD

**Issue by MohammadYounes** [rtsao/postcss-rtlcss-combined#9]
Input:

``` CSS
div {
    display: block;   
}

div {
    padding: 5px;   
}
```

Produces:

``` CSS
html[dir] div {
    padding: 5px
}
```
